<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/teacher.js' type='text/javascript'></script>
<script type="text/javascript" src="/js/my97datepicker/WdatePicker.js" ></script>
<script type="text/javascript" src="/js/swfupload/swfupload.js"></script>
<script type="text/javascript" src="/js/swfupload/jquery.swfupload.js"></script>
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table content-->
        <form action="/teacher/save" method="post" onsubmit="return Teacher.check();">
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
   	  	  <div style="font-weight:bold;border: 1px solid #dddddd; line-height:22px;">基本信息  <span style="cursor:pointer;" id="span_base" onclick="Teacher.showhideByAdd('base','table_teacher_base');" value="1" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_base">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">英文名：</td>
                        <td width="300"  style="text-align:left;"><input type="text" name="en_name" id="en_name" /></td>
                      <td width="150"  style="text-align:right;">中文名：</td>
                        <td width="300"  style="text-align:left;">
                            <input type="text" name="cn_name" id="cn_name" />
                            <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">性别：</td>
                        <td  style="text-align:left;">
                        <select name="sex" size="1" id="sex">
                          <option value="0">无</option>
                          <option value="1">男</option>
                          <option value="2">女</option>
                        </select>
                        <font color="red">*</font>
                        </td>
                      <td  style="text-align:right;">出生日期：</td>
                        <td  style="text-align:left;">
                            <input type="text" name="birthday" id="birthday" class="Wdate" onclick="WdatePicker()"/>
                            <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">住址：</td>
                        <td colspan="3"  style="text-align:left;">
                            <input name="address" type="text" id="address" size="50" />
                            <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">证件类型：</td>
                        <td  style="text-align:left;">
                        <select name="id_type" size="1" id="id_type">
                          <option value="0" selected="selected">其他</option>
                          <option value="1">身份证</option>
                          <option value="2">临时身份证</option>
                          <option value="3">护照</option>
                          <option value="4">军人证</option>
                          <option value="5">驾驶证</option>
                        </select>
                        <font color="red">*</font>
                      </td>
                      <td  style="text-align:right;">证件号码：</td>
                        <td  style="text-align:left;">
                            <input type="text" name="id_name" id="id_name" />
                            <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">联系电话：</td>
                        <td  style="text-align:left;"><input type="text" name="phone" id="phone" /></td>
                        <td  style="text-align:right;">手机：</td>
                        <td  style="text-align:left;">
                            <input type="text" name="mobile_phone" id="mobile_phone" />
                            <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">邮箱：</td>
                        <td  style="text-align:left;"><input type="text" name="email" id="email" /></td>
                        <td  style="text-align:right;">毕业院校：</td>
                        <td  style="text-align:left;"><input type="text" name="graduate_school" id="graduate_school" /></td>
                    </tr>
                    
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">毕业日期：</td>
                      <td  style="text-align:left;"><input type="text" name="graduate_date" id="graduate_date" class="Wdate" onclick="WdatePicker()"/></td>
                      <td  style="text-align:right;">毕业专业：</td>
                      <td  style="text-align:left;"><input type="text" name="graduate_specialty" id="graduate_specialty" /></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">最高学历：</td>
                      <td colspan="3"  style="text-align:left;">
                      <select name="max_educatio" size="1" id="max_educatio">
                        <option value="0" selected="selected">无</option>
                        <option value="1">大专</option>
                        <option value="2">本科</option>
                        <option value="3">重点</option>
                        <option value="4">研究生</option>
                        <option value="5">硕士</option>
                        <option value="6">博士</option>
                        <option value="7">博士后</option>
                      </select>
                      </td>
                    </tr>
                </tbody>
            </table>
            
            
            
       	    <div style="font-weight:bold; border: 1px solid #dddddd; line-height:22px;">在园信息  <span id="span_school" onclick="Teacher.showhideByAdd('school','table_teacher_school');" value="1" style="cursor:pointer;" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_school">
                <tbody>
                	<tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">所属班级：</td>
                        <td width="300"  style="text-align:left;">
                        <select name="class_id" size="1" id="class_id">
                        <option value="0">请选择</option>
                        <?php foreach($this->classData as $p):?>
                        <option value="<?=$p['class_id']?>"><?=$p['class_name']?>[<?=$p['class_no']?>]</option>
                        <?php endforeach;?>
                        </select></td>
                      <td width="150"  style="text-align:right;"><span style="text-align:right; width:150px;">教工类别</span>：</td>
                        <td width="300"  style="text-align:left;">
                        <select name="teacher_type_id" size="1" id="teacher_type_id">
                        <option value="0">请选择</option>
                        <?php foreach($this->teacherTypeData as $k=>$p):?>
                        <option value="<?=$k?>"><?=$p?></option>
                        <?php endforeach;?>
                        </select>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;"><span style="text-align:right;">岗位信息</span>：</td>
                        <td width="300"  style="text-align:left;">
                        <select name="job_id" size="1" id="job_id">
                        <option value="0">请选择</option>
                        <?php foreach($this->jobData as $p):?>
                        <option value="<?=$p['job_id']?>"><?=$p['job_name']?></option>
                        <?php endforeach;?>
                     	</select>
                        <font color="red">*</font>    
                        </td>
                        <td width="150"  style="text-align:right;"><span style="text-align:right; width:150px;">入职日期</span>：</td>
                        <td width="300"  style="text-align:left;">
                            <input type="text" name="job_date" id="job_date" class="Wdate" onclick="WdatePicker()"/>
                            <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;"><span style="text-align:right;">签订合同上一次生效起始日期</span>：</td>
                        <td  style="text-align:left;"><input type="text" name="bargain_start_date2" id="bargain_start_date2" class="Wdate" onclick="WdatePicker()"/></td>
                        <td  style="text-align:right;">签订合同上一次生效结束日期：</td>
                        <td  style="text-align:left;"><input type="text" name="bargain_end_date" id="bargain_end_date" class="Wdate" onclick="WdatePicker()"/></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">签订合同次数：</td>
                        <td  style="text-align:left;"><input type="text" name="bargain_count" id="bargain_count" /></td>
                        <td  style="text-align:right;"><span style="text-align:right; width:150px;">离职日期</span>：</td>
                        <td  style="text-align:left;">
                        <input type="text" name="leave_date" id="leave_date" class="Wdate" onclick="WdatePicker()"/>
                        （填写离职日期则状态默认为离职状态。）
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;"><span style="text-align:right;">离职原因</span>：</td>
                        <td colspan="3"  style="text-align:left;"><input name="leave_reason" type="text" id="leave_reason" size="50" /></td>
                    </tr>
                </tbody>
            </table>
            <div align="center">
            <input type="submit" name="save" value="确定提交" />
            &nbsp;&nbsp;
            <input type="button" name="fanhui" value="返回教工列表" onclick="window.location='/teacher/list'" />
            </div>
        </div>
        </form>
        <!--body table content-->


    </div>
    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
    </div>
</div>