<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/teacher.js' type='text/javascript'></script>
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table content-->
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
   	  	  <div style="font-weight:bold;border: 1px solid #dddddd; line-height:22px;">基本信息  <span style="cursor:pointer;" id="span_base" onclick="Teacher.showhideByAdd('base','table_teacher_base');" value="1" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_base">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">英文名：</td>
                        <td width="300"  style="text-align:left;"><?=$this->teacherData['en_name']?></td>
                      <td width="150"  style="text-align:right;">中文名：</td>
                        <td width="300"  style="text-align:left;"><?=$this->teacherData['cn_name']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">性别：</td>
                        <td  style="text-align:left;">
                        	<?php 
							if($this->teacherData['sex']==0) { 
								echo "无";
							} elseif($this->teacherData['sex']==1) { 
								echo "男";
							} else { 
								echo "女";
							}
							?>
                        </td>
                      <td  style="text-align:right;">出生日期：</td>
                        <td  style="text-align:left;"><?=$this->teacherData['birthday']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">住址：</td>
                        <td colspan="3"  style="text-align:left;"><?=$this->teacherData['address']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">证件类型：</td>
                      <td  style="text-align:left;">
					  <?php 
							if($this->teacherData['id_type']==0) { 
								echo "其他";
							} elseif($this->teacherData['id_type']==1) { 
								echo "身份证";
							} elseif($this->teacherData['id_type']==2) { 
								echo "临时身份证";
							} elseif($this->teacherData['id_type']==3) { 
								echo "护照";
							} elseif($this->teacherData['id_type']==4) { 
								echo "军人证";
							} elseif($this->teacherData['id_type']==5) { 
								echo "驾驶证";
							}
							?>
                      </td>
                      <td  style="text-align:right;">证件号码：</td>
                      <td  style="text-align:left;"><?=$this->teacherData['id_number']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">联系电话：</td>
                      <td  style="text-align:left;"><?=$this->teacherData['phone']?></td>
                      <td  style="text-align:right;">手机：</td>
                      <td  style="text-align:left;"><?=$this->teacherData['mobile_phone']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">邮箱：</td>
                      <td  style="text-align:left;"><?=$this->teacherData['email']?></td>
                      <td  style="text-align:right;">毕业院校：</td>
                      <td  style="text-align:left;"><?=$this->teacherData['graduate_school']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">毕业日期：</td>
                      <td  style="text-align:left;"><?=$this->teacherData['graduate_date']?></td>
                      <td  style="text-align:right;">毕业专业：</td>
                      <td  style="text-align:left;"><?=$this->teacherData['graduate_specialty']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">最高学历：</td>
                      <td colspan="3"  style="text-align:left;">
                      	<?php 
							switch($this->teacherData['max_education']) { 
								case 1:
									echo "大专";
									break;
								case 2:
									echo "本科";
									break;
								case 3:
									echo "重点";
									break;
								case 4:
									echo "研究生";
									break;
								case 5:
									echo "硕士";
									break;
								case 6:
									echo "博士";
									break;
								case 7:
									echo "博士后";
									break;
								default:
									echo "无";
									break;
							}
						?>
                      </td>
                    </tr>
                </tbody>
            </table>
            
            
<div style="font-weight:bold; border: 1px solid #dddddd; line-height:22px;">照片信息  <span id="span_photo" onclick="Teacher.showhideByAdd('photo','table_teacher_photo');" value="1" style="cursor:pointer;" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_photo">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td colspan="4"  style="text-align:center; height:150px;">
                          <div align="center">
			    			<a href="/images/<?php echo !empty($this->teacherData['photo_name'])?"teacher_photo/".$this->teacherData['photo_name']:"no_user.jpg"?>" target="_blank" id="href_teacher_photo" title="点击查看大图">
                            <img src="/images/<?php echo !empty($this->teacherData['photo_name'])?"teacher_photo/_thumb_".$this->teacherData['photo_name']:"no_user.jpg"?>" id="img_teacher_photo"  alt="点击查看大图" width="130" height="150"/>
                            </a>
                          </div>
                      </td>
                    </tr>
                </tbody>
            </table>
            
          
       	    <div style="font-weight:bold; border: 1px solid #dddddd; line-height:22px;">在园信息  <span id="span_school" onclick="Teacher.showhideByAdd('school','table_teacher_school');" value="1" style="cursor:pointer;" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_school">
                <tbody>
                	<tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">所属班级：</td>
                        <td width="300"  style="text-align:left;">
						<?=$this->teacherData['sch_class_name']?>[<?=$this->teacherData['sch_class_no']?>]
                        </td>
                      	<td width="150"  style="text-align:right;">教工类别：</td>
                        <td width="300"  style="text-align:left;"><?=$this->teacherData['ad_user_type_name']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">岗位信息：</td>
                      <td  style="text-align:left;"><?=$this->teacherData['sch_job_name']?></td>
                      <td  style="text-align:right;">入职日期：</td>
                      <td  style="text-align:left;"><?=$this->teacherData['job_date']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">签订合同上一次生效起始日期：</td>
                      <td  style="text-align:left;"><?=$this->teacherData['bargain_start_date']?></td>
                      <td  style="text-align:right;">签订合同上一次生效结束日期：</td>
                      <td  style="text-align:left;"><?=$this->teacherData['bargain_end_date']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">签订合同次数：</td>
                      <td  style="text-align:left;"><?=$this->teacherData['bargain_count']?></td>
                      <td  style="text-align:right;">离职日期：</td>
                      <td  style="text-align:left;"><?=$this->teacherData['leave_date']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">离职原因：</td>
                        <td colspan="3"  style="text-align:left;"><?=$this->teacherData['leave_reason']?></td>
               	    </tr>
                </tbody>
            </table>
    		<div align="center">&nbsp;&nbsp;
   			  <input type="button" name="fanhui" value="返回教工列表" 
                 		onclick="window.location='/teacher/list<?=urldecode(base64_decode($this->from))?>'" />
       	  </div>
        </div>
        </form>
        <!--body table content-->


    </div>
    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
    </div>
</div>