<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" id="ccc_document">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<script src="/js/js.php?v=101" type="text/javascript"></script>
<script type="text/javascript" src="/js/jquery.extend.js"></script>
<link href="/css/default.css" media="screen" rel="stylesheet" type="text/css" />

<?=$this->headTitle(" - 明日东方科技")?>
<?=$this->headLink()?>
<?=$this->headScript()?>

<script type="text/javascript" src="/js/layer/layer.min.js" ></script>

</head>
<body >
<div id="mainDiv" style="height: 600px; ">
    <div class="main-cont">
    <div class="set-area">
	    <?=$this->layout()->content?>
	</div>
    </div>
</div>

</body>
</html>