<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
	
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<?php $this->headScript()->appendFile('/js/jquery-1.9.1.min.js')?>
<?php $this->headScript()->appendFile('/js/common.js')?>
<?php $this->headLink()->appendStylesheet('/css/ccc/pop.css')?>
<?=$this->headTitle()?>
<?=$this->headLink()?>
<?=$this->headScript()?>
</head>
<body>
<?=$this->layout()->content?>
</body>
</html>