<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 55%;float: left">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table header-->

        <!--body table header-->

        <!--body table content-->
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150px;"  style="text-align:right;">权限名：</td>
                        <td colspan="2"  style="text-align:left;">
                            <input name="input_rightname" type="text" id="input_rightname" size="30" />
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right;">描述：</td>
                        <td colspan="2"  style="text-align:left;">
                            <input name="input_comments" type="text" id="input_comments" size="30" /></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td colspan="3"  style="text-align:center;">
                            <input type="button" name="button" id="button" value="添加权限信息" onclick="Auth.saveRightInfo();"/>
                        </td>
                    </tr>
                </tbody>
            </table>
    </div>
        <!--body table content-->

    </div>



    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
    </div>

</div>