<?= $this->headTitle( $this->title ) ?>
<script src='/js/<?=$GLOBALS['module']?>/auth.js' type='text/javascript'></script>
<!--条件-->
<form action="/auth/list" method="post">
<div style="font-size: 11px;">
	权限名：
	<input type="text" id="right_name" name="right_name" style="width:120px;"  value="<?=$this->rightName?>" title="支持模糊查询" />
	<button type="submit" id="submitButton" style="margin-left:10px;">
		Search
	</button>
    <button type="button" id="addButton" style="margin-left:10px;" onclick="Auth.add();">
		添加权限
	</button>
</div>
</form>

<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 40%;float: left">
	<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

		<!--body table header-->
		<div class="ui-state-default ui-jqgrid-hdiv" style="width: 100%;">
			<table class="ui-jqgrid-htable" style="width:100%" cellspacing="0" cellpadding="0" border="0">
				<thead>
					<tr class="ui-jqgrid-labels">
						<th class="ui-state-default ui-th-column ui-th-ltr">权限名</th>
						<th class="ui-state-default ui-th-column ui-th-ltr">描述</th>
                        <th class="ui-state-default ui-th-column ui-th-ltr">操作</th>
					</tr>
				</thead>
			</table>
		</div>
		<!--body table header-->

		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
			<table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
				<tbody>
					<?php foreach( $this->data as $v ): ?>
                     <tr class="ui-widget-content jqgrow ui-row-ltr" style="cursor:pointer" onclick="Auth.edit(<?=$v['right_id']?>)">
                        <td  style="text-align:center;" id="td_rightname_<?=$v['right_id']?>">
						<?=$v['right_name']?>
                        </td>
						<td  style="text-align:center;" id="td_comments_<?=$v['right_id']?>">
						<?=$v['comments']?>
                        </td>
                        <td  style="text-align:center;" onclick="if(window.confirm('确定删除吗?')){Auth.delete(<?=$v['right_id']?>,'<?=$this->from?>')}else{return false;}">
						删除
                        </td>
					</tr>
					<?php endforeach ; ?>
                </tbody>
			</table>
		</div>
		<!--body table content-->

	</div>

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
    	<div class="ui-pager-control">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-pg-table" style="width:100%;table-layout:fixed;height:100%;">
                <tbody>
                    <tr>
                        <td id="pager1_left" align="left"></td>
                        <td id="pager1_center" align="center"
                            style="white-space: pre;
                            width: 228px;"><?= $this->render('page.phtml') ?></td>
                        <td id="pager1_right" align="right"></td></tr>
                </tbody>
            </table>
        </div>
	</div>
</div>
<div id="div_right"></div>