<?= $this->headTitle( $this->title ) ?>
<!--条件-->
<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 35%;float: left">
	<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
<!--body table title-->

		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
			<table width="109%" border="0" cellpadding="0" cellspacing="0" class="ui-jqgrid-btable" style="width: 100%;">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td style="text-align:right; width:100px;">原密码：</td>
                        <td style="text-align:left; width:150px;">
                        <input type="text" name="old_pass" id="old_pass" />
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:100px;">新密码：</td>
                        <td  style="text-align:left;">
                          <input type="text" name="new_pass" id="new_pass" />
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:100px;">再输入新密码：</td>
                      <td  style="text-align:left;">
                        <input type="text" name="two_newpass" id="two_newpass" />                      	
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td colspan="2"  style="text-align:center; width:150px;">
                      <input type="button" name="button" id="button" value=" 确定修改密码 " onclick="My.updatepass()"/>
                      </td>
                    </tr>
                </tbody>
            </table>
		</div>
		<!--body table content-->

	</div>

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>
</div>
<div id="div_user"></div>