<?= $this->headTitle( $this->title ) ?>
<script src='/js/<?=$GLOBALS['module']?>/my.js' type='text/javascript'></script>
<!--条件-->
<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 60%;float: left">
	<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title1 ?></span>
		</div>
<!--body table title-->

		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
			<table width="109%" border="0" cellpadding="0" cellspacing="0" class="ui-jqgrid-btable" style="width: 100%;">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td style="text-align:right; width:150px;">用户编号：</td>
                        <td style="text-align:left; width:150px;"><?=$this->myInfo['user_id']?></td>
                        <td style="text-align:right;width:150px;">用户名（用户名称）：</td>
                        <td  style="text-align:left;"><?=$this->myInfo['user_name']?>(<?=$this->myInfo['real_name']?>)</td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">IP：</td>
                        <td colspan="3"  style="text-align:left;"><?=$this->myInfo['ip']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">添加方式：</td>
                      <td colspan="3"  style="text-align:left;">
                      	<?php
                        	if($this->myInfo['user_type']==0) { 
								echo "后台新增";
							} elseif( $this->myInfo['user_type']==1 || $this->myInfo['user_type']==2 ) { 
								echo "教工转至";
							} elseif( $this->myInfo['user_type']==3 ) { 
								echo "学生转至";
							} elseif( $this->myInfo['user_type']==7 ) { 
								echo "家长转至";
							}
						?>
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">状态：</td>
                      <td colspan="3"  style="text-align:left;">
                      	<?php 
							if($this->myInfo['status']==2) { 
								echo "未激活";
							} elseif( $this->myInfo['status']==1 ) { 
								echo "已激活";
							} elseif( $this->myInfo['status']==3 ) { 
								echo "已冻结";
							} elseif( $this->myInfo['status']==4 ) { 
								echo "已删除";
							}
						?>
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">上次登录时间</td>
                      <td  style="text-align:left;"><?=date("Y-m-d H:i",$this->myInfo['login_time'])?></td>
                      <td  style="text-align:right;">上次登出时间：</td>
                      <td  style="text-align:left;"><?=date("Y-m-d H:i",$this->myInfo['logout_time'])?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">当前登录状态：</td>
                      <td  style="text-align:left;">
                      	<?php 
							if($this->myInfo['login_status']==0) { 
								echo "未登录";
							} elseif( $this->myInfo['login_status']==1 ) { 
								echo "已登录";
							}
						?>
                      </td>
                      <td  style="text-align:right;">添加时间：</td>
                      <td  style="text-align:left;"><?=date("Y-m-d H:i",$this->myInfo['add_time_int'])?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td colspan="4"  style="text-align:center; width:150px;">
                      <input type="button" name="button" id="button" value=" 修改密码信息 " onclick="My.getpass()"/>
                      </td>
                    </tr>
                </tbody>
            </table>
		</div>
		<!--body table content-->

	</div>

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>
</div>
<div id="div_my"></div>