<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 35%;float: left">
<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

        <!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
		  <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
		    <tbody>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td width="100px"  style="text-align:right;">选择学生：</td>
                       <td style="text-align:left;">
                       <select name="input_student_id" id="input_student_id" style="width:120px;" disabled>
                       <option value="0">-请选择-</option>
                       <?php if($this->studentData):?>
                       <?php foreach($this->studentData as $p):?>
                       <option value="<?=$p['student_id']?>" <?php echo $this->data['sch_student_id']==$p['student_id']?"selected":"";?>><?=$p['cn_name']?>[<?=$p['student_no']?>]</option>
                       <?php endforeach;?>
                       <?php endif;?>
                       </select>
                       <font color="red">*</font>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  width="100px"  style="text-align:right;">处理类型：</td>
                       <td  style="text-align:left;">
                       <select name="input_type_id" id="input_type_id" style="width:120px;" disabled>
                       <option value="1" <?php echo $this->data['type_id']==1?"selected":"";?>>奖励</option>
                       <option value="2" <?php echo $this->data['type_id']==2?"selected":"";?>>惩罚</option>
                       </select>
                       <font color="red">*</font>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">处理名称：</td>
                       <td  style="text-align:left;">
                       <input name="input_deal_name" type="text" id="input_deal_name" size="35" value="<?=$this->data['deal_name']?>"/>
                       <font color="red">*</font>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">处理日期：</td>
                       <td  style="text-align:left;">
                       <input name="input_deal_date" type="text" id="input_deal_date" size="20" class="Wdate" onclick="WdatePicker()" value="<?=$this->data['deal_date']?>" disabled/>
                       <font color="red">*</font>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">处理事由：</td>
                       <td  style="text-align:left;">
                       <textarea name="input_deal_reason" id="input_deal_reason" cols="30" rows="3"><?=$this->data['deal_reason']?></textarea>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td colspan="2"  style="text-align:center;">
                       <input type="button" name="button" value="确定提交" onclick="StudentDeal.update(<?=$this->data['student_deal_data_id']?>);"/>			
                       </td>
                     </tr>
              </tbody>
		  </table>
            
	</div>
		<!--body table content-->
        
  </div>
    

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>

</div>