<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 35%;float: left">
<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

        <!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
		  <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
		    <tbody>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td width="100px"  style="text-align:right;">学生：</td>
                       <td style="text-align:left;">
                       <?=$this->dealRowData['sch_student_name']?>[<?=$this->dealRowData['sch_student_no']?>]
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  width="100px"  style="text-align:right;">处理类型：</td>
                       <td  style="text-align:left;"><?php echo $this->dealRowData['type_id']==1?"奖励":"处罚";?></td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">处理名称：</td>
                       <td  style="text-align:left;"><?=$this->dealRowData['deal_name']?></td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">处理日期：</td>
                       <td  style="text-align:left;"><?=$this->dealRowData['deal_date']?></td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">处理事由：</td>
                       <td  style="text-align:left;"><?=$this->dealRowData['deal_reason']?></td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td colspan="2"  style="text-align:center;">
                       <input type="button" name="button" value="返回" onclick="window.location='/studentdeal/my.list<?=urldecode(base64_decode($this->from))?>'"/>			
                       </td>
                     </tr>
              </tbody>
		  </table>
            
	</div>
		<!--body table content-->
        
  </div>
    

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>

</div>