<?= $this->headTitle( $this->title ) ?>
<script src="/js/my97datepicker/WdatePicker.js" type="text/javascript"></script>
<script src='/js/<?=$GLOBALS['module']?>/studentdeal.js' type='text/javascript'></script>
<!--条件-->
<form action="/studentdeal/my.list" method="post">
<div style="font-size: 11px;">
	开始日期：
    <input type="text" id="start_date" name="start_date" value="<?=$this->startDate?>" class="Wdate" onclick="WdatePicker()" style="width:80px;"/>
    结束日期：
    <input type="text" id="end_date" name="end_date" value="<?=$this->endDate?>" class="Wdate" onclick="WdatePicker()" style="width:80px;"/>
    <button type="submit" id="submitButton" style="margin-left:10px;">
		Search
	</button>
</div>
</form>

<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 60%;float: left">
	<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

		<!--body table header-->
		<div class="ui-state-default ui-jqgrid-hdiv" style="width: 100%;">
			<table class="ui-jqgrid-htable" style="width:100%" cellspacing="0" cellpadding="0" border="0">
			<thead>
			<tr class="ui-jqgrid-labels">
			<th class="ui-state-default ui-th-column ui-th-ltr" style=" width:10%;">编号</th>
            <th class="ui-state-default ui-th-column ui-th-ltr" style=" width:15%;">处理日期</th>
            <th class="ui-state-default ui-th-column ui-th-ltr" style=" width:10%;">处理类型</th>
            <th class="ui-state-default ui-th-column ui-th-ltr" style=" width:20%;">处理名称</th>
            <th class="ui-state-default ui-th-column ui-th-ltr" style=" width:10%;">处理人</th>
            <th class="ui-state-default ui-th-column ui-th-ltr" style=" width:10%;">操作</th>
			</tr>
			</thead>
			</table>
                </div>
		<!--body table header-->

		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
			<table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
				<tbody>
					<?php foreach( $this->data as $v ): ?>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:center; width:10%;">
                        <a href="##" onclick="StudentDeal.view(<?=$v['student_deal_data_id']?>,'<?=$this->from?>')">
							<?=$v['student_deal_data_id']?>
                        </a>
                        </td>
                        <td  style="text-align:center; width:15%;">
                            <?php echo !empty($v['deal_date'])?$v['deal_date']:"-";?>
                        </td>
                        <td  style="text-align:center; width:10%;">
                        	<?php if($v['type_id']==1):?>奖励
                            <?php elseif($v['type_id']==2):?>惩罚
                            <?php endif;?>
                        </td>
                        <td  style="text-align:center; width:20%;"><?=$v['deal_name']?></td>
                        <td  style="text-align:center; width:10%;"><?=$v['deal_real_name']?></td>
                        <td  style="text-align:center; width:10%;">
                        <a href="##" onclick="StudentDeal.view(<?=$v['student_deal_data_id']?>,'<?=$this->from?>')">
							查看
                        </a>
                        </td>
                    </tr>
					<?php endforeach ; ?>
                </tbody>
			</table>
  		</div>
		<!--body table content-->

	</div>

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
     <div class="ui-pager-control">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-pg-table" style="width:100%;table-layout:fixed;height:100%;">
                <tbody>
                    <tr>
                        <td id="pager1_left" align="left"></td>
                        <td id="pager1_center" align="center"
                            style="white-space: pre;
                            width: 228px;"><?= $this->render('page.phtml') ?></td>
                        <td id="pager1_right" align="right"></td></tr>
                </tbody>
            </table>
        </div>
	</div>
</div>
<div id="div_studentdeal"></div>