<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 35%;float: left">
<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
		  <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
		    <tbody>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;" width="100">属性：</td>
                       <td  style="text-align:left;">
                       <?php echo $this->classData['property']==0?"普通班":"特长班";?>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td style="text-align:right;" id="td_special">班主任：</td>
                       <td  style="text-align:left;">
                      <?php 
					  	if($this->classData['sch_teacher_id']>0) { 
							echo $this->classData['sch_teacher_name'] . "[" . $this->classData['sch_teacher_no'] . "]";
						} else { 
							echo "-";
						}
					  ?>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td style="text-align:right;">班级名称：</td>
                       <td  style="text-align:left;">
                         <?=$this->classData['class_name']?>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">人数：</td>
                       <td  style="text-align:left;">
                       <?=$this->classData['amount']?>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td style="text-align:right;">课时：</td>
                       <td style="text-align:left;">
                       <?=$this->classData['class_minute']?>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td style="text-align:right;">上课地点：</td>
                       <td style="text-align:left;">
                       <?=$this->classData['class_address']?>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td style="text-align:right;">上课时间：</td>
                       <td style="text-align:left;">
                        <?=$this->classData['class_time']?>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td style="text-align:right;">开班日期：</td>
                       <td style="text-align:left;">
                       <?=$this->classData['open_date']?>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">描述：</td>
                       <td  style="text-align:left;">
                       <?=$this->classData['comments']?>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td colspan="2"  style="text-align:center;">
                       <input type="button" name="button" 
                       	value="返回班级列表" onclick="window.location='/class/list<?=urldecode(base64_decode($this->from))?>'"/>			
                       </td>
                     </tr>
              </tbody>
		  </table>
            
	</div>
	<!--body table content-->
  	</div>
    

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>

</div>