<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/class.js' type='text/javascript'></script>
<script type="text/javascript" src="/js/my97datepicker/WdatePicker.js" ></script>
<!--条件-->
<form action="/class/list" method="post">
    <div style="font-size: 11px;">
        班级名称：
        <input type="text" id="class_name" name="class_name" value="<?= $this->className ?>" style="width:80px;"/>
        <button type="submit" id="submitButton" style="margin-left:10px;">
            Search
        </button>
        <button type="button" id="addButton" style="margin-left:5px;" onclick="Class.add();">
            添加班级信息
        </button>
    </div>
</form>

<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 60%;float: left">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table header-->
        <div class="ui-state-default ui-jqgrid-hdiv" style="width: 100%;">
            <table class="ui-jqgrid-htable" style="width:100%" cellspacing="0" cellpadding="0" border="0">
                <thead>
                    <tr class="ui-jqgrid-labels">
                        <th class="ui-state-default ui-th-column ui-th-ltr" style=" width:8%;">编号</th>
                      	<th class="ui-state-default ui-th-column ui-th-ltr" style=" width:20%;">班主任/授课教师</th>
                        <th class="ui-state-default ui-th-column ui-th-ltr" style=" width:10%;">属性</th>
                        <th class="ui-state-default ui-th-column ui-th-ltr" style=" width:15%;">班级名称</th>
                        <th class="ui-state-default ui-th-column ui-th-ltr" style=" width:10%;">人数</th>
                        <th class="ui-state-default ui-th-column ui-th-ltr" style=" width:10%;">状态</th>
                        <th class="ui-state-default ui-th-column ui-th-ltr" style=" width:10%;">操作</th>
                    </tr>
                </thead>
            </table>
</div>
        <!--body table header-->

        <!--body table content-->
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
                <tbody>
                    <?php foreach ($this->data as $v): ?>
                        <tr class="ui-widget-content jqgrow ui-row-ltr">
                          <td  style="text-align:center; width:8%;"><?=$v['class_id']?></td>
                            <td  style="text-align:center; width:20%;">
                             	<?= $v['sch_teacher_name'] ?>[<?=$v['sch_teacher_no']?>]
                            </td>
                            <td  style="text-align:center; width:10%;">
                            	<?php echo $v['property']==0?"普通班":"特长班";?>
                            </td>
                            <td  style="text-align:center; width:15%;"><?=$v['class_name']?></td>
                            <td  style="text-align:center; width:10%;"><?=$v['amount']?></td>
                            <td  style="text-align:center; width:10%;">
                               	<?php
                                	if($v['status']==0) { 
										echo "未激活";
									} elseif($v['status']==1) { 
										echo "激活";
									} elseif($v['status']==2) { 
										echo "合并";
									} elseif($v['status']==3) { 
										echo "撤销";
									} elseif($v['status']==4) { 
										echo "升级";
									}
								?>
                            </td>
                            <td  style="text-align:center; width:10%;">
                               	<?php if($v['property']==1):?>
                                <a href="##" onclick="class.sign(<?=$v['class_id']?>)" 
                                	title="特长班'<?=$v['class_name']?>'报名">报名</a> |
                                <?php endif;?>
                                删除
                            </td>
                        </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
    </div>
        <!--body table content-->

    </div>

    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
        <div class="ui-pager-control">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-pg-table" style="width:100%;table-layout:fixed;height:100%;">
                <tbody>
                    <tr>
                        <td id="pager1_left" align="left"></td>
                        <td id="pager1_center" align="center"
                            style="white-space: pre;
                            width: 228px;"><?= $this->render('page.phtml') ?></td>
                        <td id="pager1_right" align="right"></td></tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div id="div_class"></div>