<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<link rel="stylesheet" type="text/css" href="/js/jquery.ui/jquery-ui-1.8.24.css" />
		<link rel="stylesheet" type="text/css" href="/js/jqGrid/css/ui.jqgrid.css" />
		<link href="/js/jquery.editable-select/jquery.editable-select.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="/js/jquery-1.8.2.min.js"></script>
		<script type="text/javascript" src="/js/jquery.extend.js"></script>
		<script type="text/javascript" src="/js/jquery.editable-select/jquery.editable-select.pack.js"></script>
		<script type="text/javascript" src="/js/jquery.ui/jquery-ui-1.8.24.min.js"></script>
		<script type="text/javascript" src="/js/jqGrid/js/i18n/grid.locale-cn.js"></script>
		<script type="text/javascript" src="/js/jqGrid/js/jquery.jqGrid.min.js"></script>
		<link rel="stylesheet" type="text/css" media="screen" href="/js/jquery.treeview/jquery.treeview.css" />
		<script src="/js/jquery.treeview/jquery.treeview.js" type="text/javascript"></script>
		<?= $this->headTitle( " - 后台管理系统 - 明日东方科技 " ) ?>
		<?= $this->headLink() ?>
		<?= $this->headScript() ?>
	<body>
		<?=$this->layout()->content?>
	</body>
</html>