<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 35%;float: left">
<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
		  <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
		    <tbody>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;" width="100">类别：</td>
                       <td  style="text-align:left;">
                       <select name="input_type_id" id="input_type_id" style="width:120px;">
                         <option value="0">无</option>
                         <option value="1">文科</option>
                         <option value="2">理科</option>
                         <option value="3">兴趣科</option>
                       </select>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td style="text-align:right;">班级：</td>
                       <td  style="text-align:left;">
                       <select name="input_class_id" id="input_class_id" style="width:120px;">
                       <option value="0">请选择</option>
                       <?php foreach($this->classData as  $p):?>
                       <option value="<?=$p['class_id']?>"><?=$p['class_name']?>[<?=$p['class_no']?>]</option>
                       <?php endforeach;?>
                       </select>
                       <font color="red">*</font>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td style="text-align:right;">科目名称：</td>
                       <td  style="text-align:left;">
                         <input type="text" name="input_subject_name" id="input_subject_name" />
                         <font color="red">*</font>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">描述：</td>
                       <td  style="text-align:left;">
                       <textarea name="input_comments" id="input_comments" cols="30" rows="3"></textarea>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td colspan="2"  style="text-align:center;">
                       <input type="button" name="button" id="button" value="确定提交" onclick="Subject.save();"/>			
                       </td>
                     </tr>
              </tbody>
		  </table>
            
		</div>
		<!--body table content-->
  	</div>
    

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>

</div>