<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 55%;float: left">
	<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title1 ?></span>
		</div>
		<!--body table title-->

		<!--body table header-->

		<!--body table header-->

		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
			<table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
				<tbody>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td width="150px"  style="text-align:right;">角色名：</td>
                       <td  colspan="2"  style="text-align:left;">
                       <input name="input_rolename" type="text" id="input_rolename" size="30" value="<?=$this->roleInfo['role_name']?>" disabled />
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">描述：</td>
                       <td colspan="2"  style="text-align:left;">
                       <input name="input_comments" type="text" id="input_comments" size="30" value="<?=$this->roleInfo['comments']?>"/></td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td colspan="3"  style="text-align:center;">
                       <input type="button" name="button" id="button" value="修改角色信息" onclick="Role.updateRoleInfo(<?=$this->roleInfo['role_id']?>);"/>
                       </td>
                     </tr>
                </tbody>
			</table>
		</div>
		<!--body table content-->
        
  </div>
    
    
    <div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title2 ?></span>
		</div>
		<!--body table title-->
		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
			<table cellspacing="0" cellpadding="0" border="0" style="width: 100%;">
                <tbody>
                    <tr>
                        <td style="text-align:center"><strong>已有权限</strong></td>
                        <td style="text-align:center"><strong>操作</strong></td>
                        <td style="text-align:center"><strong>余下权限</strong></td>
                    </tr>
                    <tr>
                        <td style="text-align:center">
                        <select name="left_select" style="height:260px;width:220px;" multiple="true" id="left_select">
						<?php foreach($this->userRole as $ur):?>
                        <option value="<?=$ur['role_id']?>"><?=$ur['role_name']?></option>
						<?php endforeach;?>
                        </select>
                        </td>
                        <td style="text-align:center">
                        <p><input type="button" value=">>" onclick="rightMoveAll();" title="将左侧全部移至右侧"></p>
                        <p><input type="button" value=">" onclick="rightMove();" title="将左侧选中项移至右侧"></p>
                        <p><input type="button" value="<" onclick="leftMove();" title="将右侧选中项移至左侧"></p>
                        <p><input type="button" value="<<" onclick="leftMoveAll();" title="将右侧全部移至左侧"></p>
                        </td>
                        <td style="text-align:center">
                        <select name="right_select" style="height:260px;width:220px;" multiple="true" id="right_select">
						<?php foreach($this->allRole as $r):?>
                        <option value="<?=$r['role_id']?>"><?=$r['role_name']?></option>
						<?php endforeach;?>
                        </select>
                        </td>
                    </tr>
                </tbody>
            </table>
		</div>
		<!--body table content-->
        <div style=" text-align:center">
            <input type="button" value="确定保存" class="button"  disabled />
        </div>
        
  </div>
   

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>

</div>