<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 35%;float: left">
<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

        <!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
		  <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
		    <tbody>
            	     <?php if($this->showTeacher==1):?>
                         <tr class="ui-widget-content jqgrow ui-row-ltr">
                           <td width="100px;"  style="text-align:right;">选择教工：</td>
                           <td  style="text-align:left;">
                           <select name="input_teacher_id" id="input_teacher_id" style="width:120px;">
                           <option value="0">-请选择-</option>
                           <?php if($this->teacherData):?>
                           <?php foreach($this->teacherData as $p):?>
                           <option value="<?=$p['teacher_id']?>"><?=$p['cn_name']?>[<?=$p['teacher_no']?>]</option>
                           <?php endforeach;?>
                           <?php endif;?>
                           </select>
                           <font color="red">*</font>
                           </td>
                         </tr>
                     <?php else:?>
                     <input type="hidden" name="input_teacher_id" id="input_teacher_id" value="<?=$this->teacherId?>" />
                     <?php endif;?>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td width="100px;" style="text-align:right;">打卡日期：</td>
                       <td  style="text-align:left;">
                       <input name="input_attendance_date" type="text" 
                       		id="input_attendance_date" size="20" class="Wdate" onclick="WdatePicker()"/>
                       <font color="red">*</font>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">到校时间：</td>
                       <td  style="text-align:left;"><input name="input_come_time" type="text" id="input_come_time" size="20" class="Wdate" onclick="WdatePicker({dateFmt:'HH:mm'})" value=""/></td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">离校时间：</td>
                       <td  style="text-align:left;"><input name="input_leave_time" type="text" id="input_leave_time" size="20" class="Wdate" onclick="WdatePicker({dateFmt:'HH:mm'})" value=""/></td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">缺勤事由：</td>
                       <td  style="text-align:left;"><textarea name="input_reason" id="input_reason" cols="30" rows="3"></textarea></td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td colspan="2"  style="text-align:center;">
                       <input type="button" name="button" id="button" value="确定提交" onclick="TeacherAttendance.save(<?=$this->showTeacher?>);"/>			
                       </td>
                     </tr>
              </tbody>
		  </table>
            
	</div>
		<!--body table content-->
        
  </div>
    

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>

</div>