<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 100%; height:100%;float: left">
<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
		  <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
		    <tbody>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;" width="100">选择</td>
                       <td width="120"  style="text-align:left;">用户</td>
                       <td width="179"  style="text-align:left;">手机</td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td style="text-align:right;"><input type="checkbox" name="checkbox2" id="checkbox2" /></td>
                       <td  style="text-align:left;">dsfasdf</td>
                       <td  style="text-align:left;">s123123</td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td style="text-align:right;"><input type="checkbox" name="checkbox" id="checkbox" /></td>
                       <td  style="text-align:left;">sdfasdss</td>
                       <td  style="text-align:left;">123123</td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td colspan="3"  style="text-align:center;">
                       </td>
                     </tr>
              </tbody>
		  </table>
            
		</div>
		<!--body table content-->
  </div>
    

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>

</div>