<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/student.js' type='text/javascript'></script>
<script type="text/javascript" src="/js/my97datepicker/WdatePicker.js" ></script>
<script type="text/javascript" src="/js/swfupload/swfupload.js"></script>
<script type="text/javascript" src="/js/swfupload/jquery.swfupload.js"></script>
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table content-->
        <form action="/money/save.config.money" method="post" onsubmit="return Teacher.check();">
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_base">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">编号：</td>
                      <td style="text-align:left;"><?=$this->smsRowData['message_send_id']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">用户类型：</td>
                        <td style="text-align:left;">
						<?php echo $this->smsRowData['type']==1?"学生":"教工";?>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">标题：</td>
                        <td  style="text-align:left;"><?=$this->smsRowData['title']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">内容：</td>
                      <td  style="text-align:left;">
					  <?=htmlspecialchars_decode($this->smsRowData['content'])?>
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">接收人编号：</td>
                      <td  style="text-align:left;"><?=$this->smsRowData['receive_user_ids']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">接收人工号：</td>
                        <td  style="text-align:left;"><?=$this->smsRowData['receive_user_nos']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">接收人名称：</td>
                      <td  style="text-align:left;"><?=$this->smsRowData['receive_user_names']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">接收人手机：</td>
                      <td  style="text-align:left;"><?=$this->smsRowData['receive_mobile_phones']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">发送人名称：</td>
                      <td  style="text-align:left;"><?=$this->smsRowData['send_user_name']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">发送时间类型：</td>
                      <td  style="text-align:left;"><?php echo $this->smsRowData['send_time_type']==0?"立即发送":"定时发送"?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">定时发送时间：</td>
                      <td  style="text-align:left;">
					  <?php echo $this->smsRowData['send_time_int']>0?date("Y-m-d H:i:s",$this->smsRowData['send_time_int']):"-";?>
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">发送结果：</td>
                      <td  style="text-align:left;">
					  <?php echo $this->smsRowData['send_result']==0?"未发送":"已发送";?>
                      </td>
                    </tr>
                </tbody>
            </table>
            
            <div align="center">&nbsp;&nbsp;
              <input type="button" name="fanhui" 
              	value="返回短信列表" 
                onclick="window.location='/sms/list<?=urldecode(base64_decode($this->from))?>'" />
          </div>
        </div>
        </form>
        <!--body table content-->


    </div>
    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
    </div>
</div>