<?= $this->headTitle( $this->title ) ?>
<script src='/js/mutli.select.js' type='text/javascript'></script>
<script src='/js/<?=$GLOBALS['module']?>/user.js' type='text/javascript'></script>
<!--条件-->
<form action="/user/list" method="post">
<div style="font-size: 11px;">
	用户名：
	<input type="text" id="user_name" name="user_name" style="width:120px;"  value="<?=$this->userName?>" title="支持模糊查询" />
	<button type="submit" id="submitButton" style="margin-left:10px;">
		Search
	</button>
    <button type="button" id="addButton" style="margin-left:10px;" onclick="User.add();">
		添加用户
	</button>
</div>
</form>

<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 40%;float: left">
	<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

		<!--body table header-->
		<div class="ui-state-default ui-jqgrid-hdiv" style="width: 100%;">
			<table class="ui-jqgrid-htable" style="width:100%" cellspacing="0" cellpadding="0" border="0">
				<thead>
					<tr class="ui-jqgrid-labels">
						<th class="ui-state-default ui-th-column ui-th-ltr">用户名</th>
						<th class="ui-state-default ui-th-column ui-th-ltr">用户名称</th>
					</tr>
				</thead>
			</table>
		</div>
		<!--body table header-->

		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
			<table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
				<tbody>
					<?php foreach( $this->data as $v ): ?>
                     <tr class="ui-widget-content jqgrow ui-row-ltr" style="cursor:pointer" onclick="User.edit(<?=$v['user_id']?>)">
                        <td  style="text-align:center;">
						<?=$v['user_name']?>
                        </td>
						<td  style="text-align:center;" id="td_<?=$v['user_id']?>">
						<?php 
							if($v['status']==1) { 
								echo "[已激活]";
							} elseif($v['status']==2) { 
								echo "[未激活]";
							} elseif($v['status']==3) { 
								echo "[已冻结]";
							} elseif($v['status']==4) { 
								echo "<font color='red'>[已删除]</font>";
							}
						?>
						<?=$v['real_name']?>
                        </td>
					</tr>
					<?php endforeach ; ?>
                </tbody>
			</table>
		</div>
		<!--body table content-->

	</div>

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>
</div>
<div id="div_user"></div>