<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/teacher.js' type='text/javascript'></script>
<script type="text/javascript" src="/js/my97datepicker/WdatePicker.js" ></script>
<script type="text/javascript" src="/js/swfupload/swfupload.js"></script>
<script type="text/javascript" src="/js/swfupload/jquery.swfupload.js"></script>
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table content-->
        <form action="/teacher/save" method="post" onsubmit="return Teacher.check();">
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
   	  	  <div style="font-weight:bold;border: 1px solid #dddddd; line-height:22px;">基本信息  <span style="cursor:pointer;" id="span_base" onclick="Teacher.showhideByAdd('base','table_teacher_base');" value="1" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_base">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">英文名：</td>
                        <td width="300"  style="text-align:left;"><input type="text" name="en_name" id="en_name" /></td>
                      <td width="150"  style="text-align:right;">中文名：</td>
                        <td width="300"  style="text-align:left;">
                            <input type="text" name="cn_name" id="cn_name" />
                            <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">性别：</td>
                        <td  style="text-align:left;">
                        <select name="sex" size="1" id="sex">
                          <option value="0">无</option>
                          <option value="1">男</option>
                          <option value="2">女</option>
                        </select>
                        <font color="red">*</font>
                        </td>
                      <td  style="text-align:right;">出生日期：</td>
                        <td  style="text-align:left;">
                            <input type="text" name="birthday" id="birthday" class="Wdate" onclick="WdatePicker()"/>
                            <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">住址：</td>
                        <td colspan="3"  style="text-align:left;">
                            <input name="address" type="text" id="address" size="50" />
                            <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">证件类型：</td>
                        <td  style="text-align:left;">
                        <select name="id_type" size="1" id="id_type">
                          <option value="0" selected="selected">其他</option>
                          <option value="1">身份证</option>
                          <option value="2">临时身份证</option>
                          <option value="3">护照</option>
                          <option value="4">军人证</option>
                          <option value="5">驾驶证</option>
                        </select>
                        <font color="red">*</font>
                      </td>
                      <td  style="text-align:right;">证件号码：</td>
                        <td  style="text-align:left;">
                            <input type="text" name="id_name" id="id_name" />
                            <font color="red">*</font>
                        </td>
                    </tr>
                </tbody>
            </table>
            
          
       	    <div style="font-weight:bold; border: 1px solid #dddddd; line-height:22px;">在园信息  <span id="span_school" onclick="Teacher.showhideByAdd('school','table_teacher_school');" value="1" style="cursor:pointer;" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_school">
                <tbody>
                	<tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">所属班级：</td>
                        <td width="300"  style="text-align:left;">
                        <select name="class_id" size="1" id="class_id">
                        <option value="0">请选择</option>
                        <?php foreach($this->classData as $p):?>
                        <option value="<?=$p['class_id']?>"><?=$p['class_name']?>[<?=$p['class_no']?>]</option>
                        <?php endforeach;?>
                        </select></td>
                      <td width="150"  style="text-align:right;"><span style="text-align:right; width:150px;">学籍状态</span>：</td>
                        <td width="300"  style="text-align:left;">
                        <select name="teacher_type_id" size="1" id="teacher_type_id">
                        <option value="0">请选择</option>
                        <?php foreach($this->teacherTypeData as $k=>$p):?>
                        <option value="<?=$k?>"><?=$p?></option>
                        <?php endforeach;?>
                        </select>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">入学日期：</td>
                        <td  style="text-align:left;">
                        <input type="text" name="job_date" id="job_date" class="Wdate" onclick="WdatePicker()"/>
                        <font color="red">*</font>
                        </td>
                   	  <td  style="text-align:right;">毕业日期：</td>
                        <td  style="text-align:left;"><input type="text" name="job_date2" id="job_date2" class="Wdate" onclick="WdatePicker()"/></td>
                    </tr>
                </tbody>
            </table>
            
          <div style="font-weight:bold;border: 1px solid #dddddd; line-height:22px;">家长信息  <span style="cursor:pointer;" id="span_base" onclick="Teacher.showhideByAdd('base','table_teacher_base');" value="1" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_base">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:left;">英文名</td>
                      <td  style="text-align:left;">中文名</td>
                      <td  style="text-align:left;">称谓</td>
                      <td  style="text-align:left;">联系电话</td>
                      <td  style="text-align:left;">联系手机</td>
                      <td  style="text-align:left;">优先短信联系</td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td style="text-align:left;"><input type="text" name="textfield2" id="textfield2" size="15" /></td>
                      <td style="text-align:left;">
                      <input type="text" name="textfield2" id="textfield2" size="15"  /></td>
                      <td style="text-align:left;">
                      <select name="teacher_type_id3" size="1" id="teacher_type_id3">
                        <option value="1">爸爸</option>
                        <option value="2">妈妈</option>
                        <option value="3">爷爷</option>
                        <option value="4">奶奶</option>
                        <option value="5">外公</option>
                        <option value="6">外婆</option>
                        <option value="7">姑姑</option>
                        <option value="8">姑父</option>
                      </select></td>
                      <td style="text-align:left;"><input type="text" name="textfield2" id="textfield2" size="15"/></td>
                      <td style="text-align:left;"><input type="text" name="textfield2" id="textfield2" size="15"/></td>
                      <td style="text-align:left;"><input type="radio" name="radio" id="radio" value="radio" /></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield3" size="15" /></td>
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield3" size="15"  /></td>
                      <td style="text-align:left;"><select name="teacher_type_id4" size="1" id="teacher_type_id4">
                        <option value="1">爸爸</option>
                        <option value="2">妈妈</option>
                        <option value="3">爷爷</option>
                        <option value="4">奶奶</option>
                        <option value="5">外公</option>
                        <option value="6">外婆</option>
                        <option value="7">姑姑</option>
                        <option value="8">姑父</option>
                      </select></td>
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield3" size="15"/></td>
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield3" size="15"/></td>
                      <td style="text-align:left;"><input type="radio" name="radio" id="radio2" value="radio" /></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield4" size="15" /></td>
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield4" size="15"  /></td>
                      <td style="text-align:left;"><select name="teacher_type_id4" size="1" id="teacher_type_id5">
                        <option value="1">爸爸</option>
                        <option value="2">妈妈</option>
                        <option value="3">爷爷</option>
                        <option value="4">奶奶</option>
                        <option value="5">外公</option>
                        <option value="6">外婆</option>
                        <option value="7">姑姑</option>
                        <option value="8">姑父</option>
                      </select></td>
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield4" size="15"/></td>
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield4" size="15"/></td>
                      <td style="text-align:left;"><input type="radio" name="radio" id="radio3" value="radio" /></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield5" size="15" /></td>
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield5" size="15"  /></td>
                      <td style="text-align:left;"><select name="teacher_type_id4" size="1" id="teacher_type_id6">
                        <option value="1">爸爸</option>
                        <option value="2">妈妈</option>
                        <option value="3">爷爷</option>
                        <option value="4">奶奶</option>
                        <option value="5">外公</option>
                        <option value="6">外婆</option>
                        <option value="7">姑姑</option>
                        <option value="8">姑父</option>
                      </select></td>
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield5" size="15"/></td>
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield5" size="15"/></td>
                      <td style="text-align:left;"><input type="radio" name="radio" id="radio4" value="radio" /></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield6" size="15" /></td>
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield6" size="15"  /></td>
                      <td style="text-align:left;"><select name="teacher_type_id4" size="1" id="teacher_type_id7">
                        <option value="1">爸爸</option>
                        <option value="2">妈妈</option>
                        <option value="3">爷爷</option>
                        <option value="4">奶奶</option>
                        <option value="5">外公</option>
                        <option value="6">外婆</option>
                        <option value="7">姑姑</option>
                        <option value="8">姑父</option>
                      </select></td>
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield6" size="15"/></td>
                      <td style="text-align:left;"><input type="text" name="textfield3" id="textfield6" size="15"/></td>
                      <td style="text-align:left;"><input type="radio" name="radio" id="radio5" value="radio" /></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td style="text-align:left;"><input type="text" name="textfield" id="textfield" size="15" /></td>
                        <td style="text-align:left;"><input type="text" name="textfield" id="textfield" size="15"  /></td>
                      <td style="text-align:left;">
                        <select name="teacher_type_id2" size="1" id="teacher_type_id2">
                          <option value="1">爸爸</option>
                          <option value="2">妈妈</option>
                          <option value="3">爷爷</option>
                          <option value="4">奶奶</option>
                          <option value="5">外公</option>
                          <option value="6">外婆</option>
                          <option value="7">姑姑</option>
                          <option value="8">姑父</option>
                        </select>
                      </td>
                        <td style="text-align:left;"><input type="text" name="textfield" id="textfield" size="15"/></td>
                        <td style="text-align:left;"><input type="text" name="textfield" id="textfield" size="15"/></td>
                        <td style="text-align:left;"><input type="radio" name="radio" id="radio" value="radio" /></td>
                    </tr>
                </tbody>
            </table>
            
            
            <div align="center">
            <input type="submit" name="save" value="确定提交" />
            &nbsp;&nbsp;
            <input type="button" name="fanhui" value="返回教工列表" onclick="window.location='/teacher/list'" />
          </div>
        </div>
        </form>
        <!--body table content-->


    </div>
    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
    </div>
</div>