<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/student.js' type='text/javascript'></script>
<script type="text/javascript" src="/js/my97datepicker/WdatePicker.js" ></script>
<script type="text/javascript" src="/js/swfupload/swfupload.js"></script>
<script type="text/javascript" src="/js/swfupload/jquery.swfupload.js"></script>
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table content-->
        <form action="/student/save" method="post" onsubmit="return Student.check();">
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
   	  	  <div style="font-weight:bold;border: 1px solid #dddddd; line-height:22px;">基本信息  <span style="cursor:pointer;" id="span_base" onclick="Student.showhideByAdd('base','table_base');" value="1" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_base">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">英文名：</td>
                        <td width="300"  style="text-align:left;"><input type="text" name="en_name" id="en_name" /></td>
                      <td width="150"  style="text-align:right;">中文名：</td>
                        <td width="300"  style="text-align:left;">
                            <input type="text" name="cn_name" id="cn_name" />
                            <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">性别：</td>
                        <td  style="text-align:left;">
                        <select name="sex" size="1" id="sex">
                          <option value="1">男</option>
                          <option value="2">女</option>
                        </select>
                        <font color="red">*</font>
                        </td>
                      <td  style="text-align:right;">出生日期：</td>
                        <td  style="text-align:left;">
                            <input type="text" name="birthday" id="birthday" class="Wdate" onclick="WdatePicker()"/>
                            <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">住址：</td>
                        <td colspan="3"  style="text-align:left;">
                            <input name="address" type="text" id="address" size="50" />
                            <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">证件类型：</td>
                        <td  style="text-align:left;">
                        <select name="id_type" size="1" id="id_type">
                          <option value="0" selected="selected">其他</option>
                          <option value="1">身份证</option>
                          <option value="2">临时身份证</option>
                          <option value="3">护照</option>
                          <option value="4">军人证</option>
                          <option value="5">驾驶证</option>
                        </select>
                        <font color="red">*</font>
                      </td>
                      <td  style="text-align:right;">证件号码：</td>
                        <td  style="text-align:left;">
                            <input type="text" name="id_name" id="id_name" />
                            <font color="red">*</font>
                        </td>
                    </tr>
                </tbody>
            </table>
            
          
       	    <div style="font-weight:bold; border: 1px solid #dddddd; line-height:22px;">在园信息  <span id="span_school" onclick="Student.showhideByAdd('school','table_school');" value="1" style="cursor:pointer;" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_school">
                <tbody>
                	<tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">所属班级：</td>
                        <td width="300"  style="text-align:left;">
                        <select name="class_id" size="1" id="class_id">
                        <option value="0">请选择</option>
                        <?php foreach($this->classData as $p):?>
                        <option value="<?=$p['class_id']?>"><?=$p['class_name']?>[<?=$p['class_no']?>]</option>
                        <?php endforeach;?>
                        </select>
                        <font color="red">*</font>
                        （选择班级只能选择普通班）
                        </td>
                      <td width="150"  style="text-align:right;"><span style="text-align:right; width:150px;">学籍状态</span>：</td>
                        <td width="300"  style="text-align:left;">
                        <select name="school_status" id="school_status">
                        <option value="0">在读</option>
                        </select>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">入学日期：</td>
                        <td colspan="3"  style="text-align:left;">
                        <input type="text" name="entrance_date" id="entrance_date" class="Wdate" onclick="WdatePicker()"/>
                        <font color="red">*</font></td>
               	    </tr>
                </tbody>
            </table>
            
    <div style="font-weight:bold;border: 1px solid #dddddd; line-height:22px;">家长信息  <span style="cursor:pointer;" id="span_parent" onclick="Student.showhideByAdd('parent','table_parent');" value="1" title="显示或隐藏">↑</span>（以下信息必须填写至少一条信息）</div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_parent">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:left;">英文名</td>
                      <td  style="text-align:left;">中文名</td>
                      <td  style="text-align:left;">称谓</td>
                      <td  style="text-align:left;">联系电话</td>
                      <td  style="text-align:left;">联系手机</td>
                      <td  style="text-align:left;">优先短信联系</td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td style="text-align:left;">
                      <input type="text" name="parent_en_name[1]" id="parent_en_name_0" size="15" />
                      </td>
                      <td style="text-align:left;">
                      <input type="text" name="parent_cn_name[1]" id="parent_cn_name_0" size="15"  /></td>
                      <td style="text-align:left;">
                      <select name="parent_named[1]" id="parent_named_0">
                        <option value="1">爸爸</option>
                        <option value="2">妈妈</option>
                        <option value="3">爷爷</option>
                        <option value="4">奶奶</option>
                        <option value="5">外公</option>
                        <option value="6">外婆</option>
                        <option value="7">姑姑</option>
                        <option value="8">姑父</option>
                      </select></td>
                      <td style="text-align:left;">
                      <input type="text" name="parent_phone[1]" id="parent_phone_0" size="15"/>
                      </td>
                      <td style="text-align:left;">
                      <input type="text" name="parent_mobile_phone[1]" id="parent_mobile_phone_0" size="15"/>
                      </td>
                      <td style="text-align:left;">
                      <select name="parent_is_message[1]" id="parent_is_message_0">
                        <option value="0">否</option>
                        <option value="1">是</option>
                      </select>
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td style="text-align:left;">
                      <input type="text" name="parent_en_name[2]" id="parent_en_name_1" size="15" />
                      </td>
                      <td style="text-align:left;">
                      <input type="text" name="parent_cn_name[2]" id="parent_cn_name_1" size="15"  /></td>
                      <td style="text-align:left;">
                      <select name="parent_named[2]" id="parent_named_1">
                        <option value="1">爸爸</option>
                        <option value="2">妈妈</option>
                        <option value="3">爷爷</option>
                        <option value="4">奶奶</option>
                        <option value="5">外公</option>
                        <option value="6">外婆</option>
                        <option value="7">姑姑</option>
                        <option value="8">姑父</option>
                      </select></td>
                      <td style="text-align:left;">
                      <input type="text" name="parent_phone[2]" id="parent_phone_1" size="15"/>
                      </td>
                      <td style="text-align:left;">
                      <input type="text" name="parent_mobile_phone[2]" id="parent_mobile_phone_1" size="15"/>
                      </td>
                      <td style="text-align:left;">
                      <select name="parent_is_message[2]" id="parent_is_message_1">
                        <option value="0">否</option>
                        <option value="1">是</option>
                      </select>
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td style="text-align:left;">
                      <input type="text" name="parent_en_name[3]" id="parent_en_name_2" size="15" />
                      </td>
                      <td style="text-align:left;">
                      <input type="text" name="parent_cn_name[3]" id="parent_cn_name_2" size="15"  /></td>
                      <td style="text-align:left;">
                      <select name="parent_named[3]" id="parent_named_2">
                        <option value="1">爸爸</option>
                        <option value="2">妈妈</option>
                        <option value="3">爷爷</option>
                        <option value="4">奶奶</option>
                        <option value="5">外公</option>
                        <option value="6">外婆</option>
                        <option value="7">姑姑</option>
                        <option value="8">姑父</option>
                      </select></td>
                      <td style="text-align:left;">
                      <input type="text" name="parent_phone[3]" id="parent_phone_2" size="15"/>
                      </td>
                      <td style="text-align:left;">
                      <input type="text" name="parent_mobile_phone[3]" id="parent_mobile_phone_2" size="15"/>
                      </td>
                      <td style="text-align:left;">
                      <select name="parent_is_message[3]" id="parent_is_message_2">
                        <option value="0">否</option>
                        <option value="1">是</option>
                      </select>
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td style="text-align:left;">
                      <input type="text" name="parent_en_name[4]" id="parent_en_name_3" size="15" />
                      </td>
                      <td style="text-align:left;">
                      <input type="text" name="parent_cn_name[4]" id="parent_cn_name_3" size="15"  /></td>
                      <td style="text-align:left;">
                      <select name="parent_named[4]" id="parent_named_3">
                        <option value="1">爸爸</option>
                        <option value="2">妈妈</option>
                        <option value="3">爷爷</option>
                        <option value="4">奶奶</option>
                        <option value="5">外公</option>
                        <option value="6">外婆</option>
                        <option value="7">姑姑</option>
                        <option value="8">姑父</option>
                      </select></td>
                      <td style="text-align:left;">
                      <input type="text" name="parent_phone[4]" id="parent_phone_3" size="15"/>
                      </td>
                      <td style="text-align:left;">
                      <input type="text" name="parent_mobile_phone[4]" id="parent_mobile_phone_3" size="15"/>
                      </td>
                      <td style="text-align:left;">
                      <select name="parent_is_message[4]" id="parent_is_message_3">
                        <option value="0">否</option>
                        <option value="1">是</option>
                      </select>
                      </td>
                    </tr>
                </tbody>
            </table>
            
            
            <div align="center">
            <input type="submit" name="save" value="确定提交" />
            &nbsp;&nbsp;
            <input type="button" name="fanhui" value="返回学生列表" onclick="window.location='/student/list'" />
          </div>
        </div>
        </form>
        <!--body table content-->


    </div>
    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
    </div>
</div>