<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/student.js' type='text/javascript'></script>
<script type="text/javascript" src="/js/my97datepicker/WdatePicker.js" ></script>
<script type="text/javascript" src="/js/swfupload/swfupload.js"></script>
<script type="text/javascript" src="/js/swfupload/jquery.swfupload.js"></script>
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table content-->
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
   	  	  <div style="font-weight:bold;border: 1px solid #dddddd; line-height:22px;">基本信息  <span style="cursor:pointer;" id="span_base" onclick="Teacher.showhideByAdd('base','table_teacher_base');" value="1" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_base">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">英文名：</td>
                        <td width="300"  style="text-align:left;"><?=$this->studentRowData['en_name']?></td>
                      <td width="150"  style="text-align:right;">中文名：</td>
                        <td width="300"  style="text-align:left;"><?=$this->studentRowData['cn_name']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">性别：</td>
                        <td  style="text-align:left;">
                        	<?php 
							if($this->studentRowData['sex']==0) { 
								echo "无";
							} elseif($this->studentRowData['sex']==1) { 
								echo "男";
							} else { 
								echo "女";
							}
							?>
                        </td>
                      <td  style="text-align:right;">出生日期：</td>
                        <td  style="text-align:left;"><?=$this->studentRowData['birthday']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">住址：</td>
                        <td colspan="3"  style="text-align:left;"><?=$this->studentRowData['address']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">证件类型：</td>
                        <td  style="text-align:left;">
                        	<?php 
							if($this->studentRowData['id_type']==0) { 
								echo "其他";
							} elseif($this->studentRowData['id_type']==1) { 
								echo "身份证";
							} elseif($this->studentRowData['id_type']==2) { 
								echo "临时身份证";
							} elseif($this->studentRowData['id_type']==3) { 
								echo "护照";
							} elseif($this->studentRowData['id_type']==4) { 
								echo "军人证";
							} elseif($this->studentRowData['id_type']==5) { 
								echo "驾驶证";
							}
							?>
                        </td>
                      	<td  style="text-align:right;">证件号码：</td>
                      	<td  style="text-align:left;"><?=$this->studentRowData['id_number']?></td>
                    </tr>
                </tbody>
            </table>
            
            
            <div style="font-weight:bold; border: 1px solid #dddddd; line-height:22px;">照片信息  <span id="span_photo" onclick="Teacher.showhideByAdd('photo','table_teacher_photo');" value="1" style="cursor:pointer;" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_photo">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td colspan="4"  style="text-align:center; height:150px;">
                          <div align="center">
			    			<a href="/images/<?php echo !empty($this->studentRowData['photo_name'])?"student_photo/".$this->studentRowData['photo_name']:"no_user.jpg"?>" target="_blank" id="href_student_photo" title="点击查看大图">
                            <img src="/images/<?php echo !empty($this->studentRowData['photo_name'])?"student_photo/_thumb_".$this->studentRowData['photo_name']:"no_user.jpg"?>" id="img_student_photo"  alt="点击查看大图" width="130" height="150"/>
                            </a>
                          </div>
                      </td>
                    </tr>
                </tbody>
            </table>
            
          
       	    <div style="font-weight:bold; border: 1px solid #dddddd; line-height:22px;">在园信息  <span id="span_school" onclick="Teacher.showhideByAdd('school','table_teacher_school');" value="1" style="cursor:pointer;" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_school">
                <tbody>
                	<tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">所属班级：</td>
                        <td width="300"  style="text-align:left;">&nbsp;</td>
                      <td width="150"  style="text-align:right;"><span style="text-align:right; width:150px;">学籍状态</span>：</td>
                        <td width="300"  style="text-align:left;">&nbsp;</td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">入学日期：</td>
                        <td  style="text-align:left;">&nbsp;</td>
                   	  <td  style="text-align:right;">毕业日期：</td>
                        <td  style="text-align:left;">&nbsp;</td>
                    </tr>
                </tbody>
            </table>
            
          <div style="font-weight:bold;border: 1px solid #dddddd; line-height:22px;">家长信息  <span style="cursor:pointer;" id="span_base" onclick="Teacher.showhideByAdd('base','table_teacher_base');" value="1" title="显示或隐藏">↑</span></div>
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_base">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:left;">英文名</td>
                      <td  style="text-align:left;">中文名</td>
                      <td  style="text-align:left;">称谓</td>
                      <td  style="text-align:left;">联系电话</td>
                      <td  style="text-align:left;">联系手机</td>
                      <td  style="text-align:left;">优先短信联系</td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                      <td style="text-align:left;">&nbsp;</td>
                    </tr>
                </tbody>
            </table>
            
            
            <div align="center">&nbsp;&nbsp;
            <input type="button" name="fanhui" value="返回学生列表" onclick="window.location='/student/list'" />
          </div>
        </div>
        </form>
        <!--body table content-->


    </div>
    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
    </div>
</div>