<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/money.js' type='text/javascript'></script>
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table content-->
        <form action="/money/save.config.money" method="post" onsubmit="return Money.checkConfigMoney();">
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_base">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">选择班级：</td>
                        <td style="text-align:left;">
                        <select name="class_id" id="class_id">
                          <option value="0">-请选择-</option>
                          <?php foreach($this->classData as $p):?>
                          <option value="<?=$p['class_id']?>"><?=$p['class_name']?>[<?=$p['class_no']?>]</option>
                          <?php endforeach;?>
                        </select>
                        <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">学期编号：</td>
                        <td  style="text-align:left;">
                        <select name="term_id" id="term_id">
                          <option value="0">-请选择-</option>
                          <?php foreach($this->termData as $p):?>
                          <option value="<?=$p['term_id']?>">[<?=$p['year']?>]<?=$p['term_name']?></option>
                          <?php endforeach;?>
                        </select>
                        <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">月份：</td>
                      <td  style="text-align:left;">
                      <select name="month" id="month">
                        <option value="0">-无-</option>
                        <option value="1">1月</option>
                        <option value="2">2月</option>
                        <option value="3">3月</option>
                        <option value="4">4月</option>
                        <option value="5">5月</option>
                        <option value="6">6月</option>
                        <option value="7">7月</option>
                        <option value="8">8月</option>
                        <option value="9">9月</option>
                        <option value="10">10月</option>
                        <option value="11">11月</option>
                        <option value="12">12月</option>
                      </select>
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">选择项目：</td>
                        <td  style="text-align:left;">
                        <select name="project_id" id="project_id">
                          <option value="0">-请选择-</option>
                          <?php foreach($this->projectData as $p):?>
                          <option value="<?=$p['money_project_id']?>"><?=$p['money_project_name']?></option>
                          <?php endforeach;?>
                        </select>
                        <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">收费金额：</td>
                      <td  style="text-align:left;">
                      <input type="text" name="money" id="money" />
                      <font color="red">*</font>
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">收费说明：</td>
                      <td  style="text-align:left;">
                      <textarea name="comments" id="comments" cols="45" rows="5"></textarea>
                      </td>
                    </tr>
                </tbody>
            </table>
            
            <div align="center">
            <input type="submit" name="save" value="确定提交" />
            &nbsp;&nbsp;
            <input type="button" name="fanhui" value="返回班级学期项目费用信息" onclick="window.location='/money/list.config.money'" />
          </div>
        </div>
        </form>
        <!--body table content-->


    </div>
    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
    </div>
</div>