<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/student.js' type='text/javascript'></script>
<script type="text/javascript" src="/js/my97datepicker/WdatePicker.js" ></script>
<script type="text/javascript" src="/js/swfupload/swfupload.js"></script>
<script type="text/javascript" src="/js/swfupload/jquery.swfupload.js"></script>
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table content-->
        <form action="/money/save.config.money" method="post" onsubmit="return Teacher.check();">
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_base">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">选择班级：</td>
                        <td style="text-align:left;">
                        <select name="id_type" size="1" id="id_type">
                          <option value="0" selected="selected">其他</option>
                          <option value="1">身份证</option>
                          <option value="2">临时身份证</option>
                          <option value="3">护照</option>
                          <option value="4">军人证</option>
                          <option value="5">驾驶证</option>
                        </select>
                        <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">学期编号：</td>
                        <td  style="text-align:left;">
                        <select name="id_type3" size="1" id="id_type3">
                          <option value="0" selected="selected">其他</option>
                          <option value="1">身份证</option>
                          <option value="2">临时身份证</option>
                          <option value="3">护照</option>
                          <option value="4">军人证</option>
                          <option value="5">驾驶证</option>
                        </select>
                        <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">选择项目：</td>
                        <td  style="text-align:left;">
                        <select name="id_type2" size="1" id="id_type2">
                          <option value="0" selected="selected">其他</option>
                          <option value="1">身份证</option>
                          <option value="2">临时身份证</option>
                          <option value="3">护照</option>
                          <option value="4">军人证</option>
                          <option value="5">驾驶证</option>
                        </select>
                        <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">收费金额：</td>
                      <td  style="text-align:left;">
                      <input type="text" name="en_name2" id="en_name2" />
                      <font color="red">*</font>
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">收费说明：</td>
                      <td  style="text-align:left;">
                      <textarea name="textarea" id="textarea" cols="45" rows="5"></textarea>
                      </td>
                    </tr>
                </tbody>
            </table>
            
            <div align="center">
            <input type="submit" name="save" value="确定提交" />
            &nbsp;&nbsp;
            <input type="button" name="fanhui" value="返回费用配置列表" onclick="window.location='/money/list.config.money'" />
          </div>
        </div>
        </form>
        <!--body table content-->


    </div>
    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
    </div>
</div>