<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 35%;float: left">
<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
		  <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
		    <tbody>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;" width="100">学年：</td>
                       <td  style="text-align:left;">
                       <select name="input_year" id="input_year" disabled>
                       	 <?php foreach($this->year as $v):?>
                         <option value="<?=$v?>" 
						 	<?php echo $v==$this->configTermData['year']?"selected":"";?>><?=$v?></option>
                         <?php endforeach;?>
                       </select>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td style="text-align:right;" id="td_special">学期名称：</td>
                       <td  style="text-align:left;">
                       <input type="text" name="input_term_name" id="input_term_name" 
                       		value="<?=$this->configTermData['term_name']?>" disabled/>
                       <font color="red">*</font>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td style="text-align:right;">学期类型：</td>
                       <td  style="text-align:left;">
                       <select name="input_type" id="input_type" disabled>
                         <option value="1" <?php echo 1==$this->configTermData['type']?"selected":"";?>>春季学期</option>
                         <option value="2" <?php echo 2==$this->configTermData['type']?"selected":"";?>>夏季学期</option>
                         <option value="3" <?php echo 3==$this->configTermData['type']?"selected":"";?>>秋季学期</option>
                         <option value="4" <?php echo 4==$this->configTermData['type']?"selected":"";?>>爱他</option>
                       </select>
                       
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">开始时间：</td>
                       <td  style="text-align:left;">
                       <input type="text" name="input_start_date" id="input_start_date"
                       		value="<?=$this->configTermData['start_date']?>"/>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td style="text-align:right;">结束时间：</td>
                       <td style="text-align:left;">
                       <input type="text" name="input_end_date" id="input_end_date" 
                         	value="<?=$this->configTermData['end_date']?>"/>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">描述：</td>
                       <td  style="text-align:left;">
                       <textarea name="input_comments" id="input_comments" 
                       		cols="30" rows="3"><?=$this->configTermData['comments']?></textarea>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td colspan="2"  style="text-align:center;">
                       <input type="button" name="button" id="button" value="确定提交"
                              onclick="Money.updateConfigTerm(<?=$this->configTermData['term_id']?>,'<?=$this->from?>');"/>			
                       </td>
                     </tr>
              </tbody>
		  </table>
            
	</div>
	<!--body table content-->
  	</div>
    

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>

</div>