<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 35%;float: left">
<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
		  <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
		    <tbody>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td width="100" style="text-align:right;">费用项目名称：</td>
                       <td  style="text-align:left;">
                         <input type="text" name="input_class_name" id="input_class_name" />
                         <font color="red">*</font>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">描述：</td>
                       <td  style="text-align:left;">
                       <textarea name="input_comments" id="input_comments" cols="30" rows="3"></textarea>
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td colspan="2"  style="text-align:center;">
                       <input type="button" name="button" id="button" value="确定提交" onclick="Class.save();"/>			
                       </td>
                     </tr>
              </tbody>
		  </table>
            
	</div>
	<!--body table content-->
  	</div>
    

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>

</div>