<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/student.js' type='text/javascript'></script>
<script type="text/javascript" src="/js/my97datepicker/WdatePicker.js" ></script>
<script type="text/javascript" src="/js/swfupload/swfupload.js"></script>
<script type="text/javascript" src="/js/swfupload/jquery.swfupload.js"></script>

<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table content-->
        <form action="/money/update.config.money" method="post" onsubmit="return Money.check();">
        <input type="hidden"  name="hidden_mc_id" id="hidden_mc_id" value="<?=$this->configMoneyData['money_config_id']?>"/>
        <input type="hidden"  name="from" id="from" value="<?=$this->from?>"/>
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_base">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">选择班级：</td>
                        <td style="text-align:left;">
                        <select name="class_id" id="class_id" disabled>
                          <option value="0">-请选择-</option>
                          <?php foreach($this->classData as $p):?>
                          <option value="<?=$p['class_id']?>" 
						  	<?php echo $this->configMoneyData['sch_class_id']==$p['class_id']?"selected":"";?>>
							<?=$p['class_name']?>[<?=$p['class_no']?>]
                          </option>
                          <?php endforeach;?>
                        </select>
                        <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">学期编号：</td>
                        <td  style="text-align:left;">
                        <select name="term_id" id="term_id" disabled>
                          <option value="0">-请选择-</option>
                          <?php foreach($this->termData as $p):?>
                          <option value="<?=$p['term_id']?>" 
						  	<?php echo $this->configMoneyData['sch_term_id']==$p['term_id']?"selected":"";?>>
                            [<?=$p['year']?>]<?=$p['term_name']?>
                          </option>
                          <?php endforeach;?>
                        </select>
                        <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">月份：</td>
                      <td  style="text-align:left;">
                      <select name="month" id="month" disabled>
                        <option value="0" <?php echo $this->configMoneyData['month']==0?"selected":"";?>>-无-</option>
                        <option value="1" <?php echo $this->configMoneyData['month']==1?"selected":"";?>>1月</option>
                        <option value="2" <?php echo $this->configMoneyData['month']==2?"selected":"";?>>2月</option>
                        <option value="3" <?php echo $this->configMoneyData['month']==3?"selected":"";?>>3月</option>
                        <option value="4" <?php echo $this->configMoneyData['month']==4?"selected":"";?>>4月</option>
                        <option value="5" <?php echo $this->configMoneyData['month']==5?"selected":"";?>>5月</option>
                        <option value="6" <?php echo $this->configMoneyData['month']==6?"selected":"";?>>6月</option>
                        <option value="7" <?php echo $this->configMoneyData['month']==7?"selected":"";?>>7月</option>
                        <option value="8" <?php echo $this->configMoneyData['month']==8?"selected":"";?>>8月</option>
                        <option value="9" <?php echo $this->configMoneyData['month']==9?"selected":"";?>>9月</option>
                        <option value="10" <?php echo $this->configMoneyData['month']==10?"selected":"";?>>10月</option>
                        <option value="11" <?php echo $this->configMoneyData['month']==11?"selected":"";?>>11月</option>
                        <option value="12" <?php echo $this->configMoneyData['month']==12?"selected":"";?>>12月</option>
                      </select>
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">选择项目：</td>
                        <td  style="text-align:left;">
                        <select name="project_id" id="project_id" disabled>
                          <option value="0">-请选择-</option>
                          <?php foreach($this->projectData as $p):?>
                          <option value="<?=$p['money_project_id']?>" 
						  	<?php echo $this->configMoneyData['sch_money_project_id']==$p['money_project_id']?"selected":"";?>>
							<?=$p['money_project_name']?>
                          </option>
                          <?php endforeach;?>
                        </select>
                        <font color="red">*</font>
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">收费金额：</td>
                      <td  style="text-align:left;">
                      <input type="text" name="money" id="money" value="<?=$this->configMoneyData['money']?>"/>
                      <font color="red">*</font>
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">收费说明：</td>
                      <td  style="text-align:left;">
                      <textarea name="comments" id="comments" cols="45" rows="5"><?=$this->configMoneyData['comments']?></textarea>
                      </td>
                    </tr>
                </tbody>
            </table>
            
            <div align="center">
            <input type="submit" name="save" value="确定提交" />
            &nbsp;&nbsp;
            <input type="button" name="fanhui" value="返回班级学期项目费用信息" 
            	onclick="window.location='/money/list.config.money<?=urldecode(base64_decode($this->form))?>'" />
          </div>
        </div>
        </form>
        <!--body table content-->


    </div>
    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
    </div>
</div>