<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/money.js' type='text/javascript'></script>
<script type="text/javascript" src="/js/my97datepicker/WdatePicker.js" ></script>
<!--条件-->
<form action="/class/list" method="post">
    <div style="font-size: 11px;">
        费用项目名称：
        <input type="text" id="class_name" name="class_name" value="<?= $this->className ?>" style="width:80px;"/>
        <button type="submit" id="submitButton" style="margin-left:10px;">
            Search
        </button>
        <button type="button" id="addButton" style="margin-left:5px;" onclick="Money.addConfigMoneyProject();">
            添加费用项目配置信息
        </button>
    </div>
</form>

<form action="/class/deal" method="post" >
<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 60%;float: left">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table header-->
        <div class="ui-state-default ui-jqgrid-hdiv" style="width: 100%;">
            <table class="ui-jqgrid-htable" style="width:100%" cellspacing="0" cellpadding="0" border="0">
                <thead>
                    <tr class="ui-jqgrid-labels">
                      <th class="ui-state-default ui-th-column ui-th-ltr" style=" width:5%;">编号</th>
                      	<th class="ui-state-default ui-th-column ui-th-ltr" style=" width:20%;">收费项目名称</th>
                        <th class="ui-state-default ui-th-column ui-th-ltr" style=" width:25%;">操作</th>
                    </tr>
                </thead>
            </table>
  </div>
        <!--body table header-->

        <!--body table content-->
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
                <tbody>
                    	<?php foreach ($this->data as $v): ?>
                        <tr class="ui-widget-content jqgrow ui-row-ltr">
                          <td  style="text-align:center; width:5%;"><?=$v['money_project_id']?></td>
                            <td  style="text-align:center; width:20%;"><?= $v['money_project_name'] ?></td>
                            <td  style="text-align:center; width:25%;">
                           	  <a href="#" onclick="Money.viewConfigMoneyProject(<?=$v['money_project_id']?>,'<?=$this->from?>')">查看</a> | 
                                <a href="#" onclick="Class.edit(<?=$v['money_project_id']?>,'<?=$this->from?>')">修改</a> | 
                                <a href="/class/delete/class_id/<?=$v['money_project_id']?>/from/<?=$this->from?>" onclick="if(window.confirm('确定删除吗?')){return true;}else{return false;}">删除</a>
                            </td>
                        </tr>
                		<?php endforeach; ?>
                </tbody>
            </table>
</div>
        <!--body table content-->
		
  </div>

    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
        <div class="ui-pager-control">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-pg-table" style="width:100%;table-layout:fixed;height:100%;">
                <tbody>
                    <tr>
                        <td id="pager1_left" align="left"></td>
                        <td id="pager1_center" align="center"
                            style="white-space: pre;
                            width: 228px;"><?= $this->render('page.phtml') ?></td>
                        <td id="pager1_right" align="right"></td></tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
</form>
<div id="div_config"></div>