<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/teacher.js' type='text/javascript'></script>


<!--条件-->
<form action="/student/list" method="post">
    <div style="font-size: 11px;">
        班级：
        <input type="text" name="en_name"  size="12" value="<?=$this->enName?>"  title="支持模糊"/>
        学期：
        <input type="text" name="cn_name"  size="12" value="<?=$this->cnName?>"  title="支持模糊"/>
        费用项目：
        <input type="text" name="cn_name"  size="12" value="<?=$this->cnName?>"  title="支持模糊"/>
        <button type="submit" id="submitButton" style="margin-left:30px;">
            Search
        </button>
        <button type="button" onclick="window.location='/money/add.config.money'">
            添加班级学期项目费用信息
        </button>
    </div>
</form>

<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table header-->
        <div class="ui-state-default ui-jqgrid-hdiv" style="width: 100%;">
            <table class="ui-jqgrid-htable" style="width:100%" cellspacing="0" cellpadding="0" border="0">
                <thead>
                    <tr class="ui-jqgrid-labels">
                    <th class="ui-state-default ui-th-column ui-th-ltr" style="width:100px;">编号</th>
                    <th class="ui-state-default ui-th-column ui-th-ltr">班级</th>
                    <th class="ui-state-default ui-th-column ui-th-ltr">学期</th>
                    <th class="ui-state-default ui-th-column ui-th-ltr">月份</th>
                    <th class="ui-state-default ui-th-column ui-th-ltr">收费项目</th>
                    <th class="ui-state-default ui-th-column ui-th-ltr">收费金额</th>
                    <th class="ui-state-default ui-th-column ui-th-ltr" style="width:200px;">操作</th>
                    </tr>
                </thead>
            </table>
    	</div>
        <!--body table header-->

        <!--body table content-->
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
                <tbody>
                    <?php foreach ($this->data as $k=>$v): ?>
                        <tr class="ui-widget-content jqgrow ui-row-ltr">
                            <td  style="text-align:center; width:100px;">
							<a href="/student/view/student_id/<?=$v['money_config_id']?>/from/<?=$this->from?>">
							<?=$v['money_config_id']?>
                            </a>
                            </td>
                            <td  style="text-align:center;"><?=$v['sch_class_name']?>[<?=$v['sch_class_no']?>]</td>
                            <td  style="text-align:center;"><?=$v['sch_term_name']?></td>
                            <td  style="text-align:center;"><?=$v['month']?></td>
                            <td  style="text-align:center;"><?=$v['sch_money_project_name']?></td>
                            <td  style="text-align:center;"><?=$v['money']?></td>
                            <td  style="text-align:center; width:200px;">
                            <a href="/money/view.config.money/mc_id/<?=$v['money_config_id']?>/from/<?=$this->from?>">查看</a> | 
                            <a href="/money/edit.config.money/mc_id/<?=$v['money_config_id']?>/from/<?=$this->from?>">修改</a> | 
                            <a href="/money/delete.config.money/mc_id/<?=$v['money_config_id']?>/from/<?=$this->from?>" onclick="if(window.confirm('确定删除吗？')){return true;}else{return false;}">删除</a>
                            </td>
                        </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
  </div>
        <!--body table content-->

    </div>

    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
        <div class="ui-pager-control">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-pg-table" style="width:100%;table-layout:fixed;height:100%;">
                <tbody>
                    <tr>
                        <td id="pager1_left" align="left"></td>
                        <td id="pager1_center" align="center"
                            style="white-space: pre;
                            width: 228px;"><?= $this->render('page.phtml') ?></td>
                        <td id="pager1_right" align="right"></td></tr>
                </tbody>
            </table>
        </div>
    </div>

</div>