<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/student.js' type='text/javascript'></script>
<script type="text/javascript" src="/js/my97datepicker/WdatePicker.js" ></script>
<script type="text/javascript" src="/js/swfupload/swfupload.js"></script>
<script type="text/javascript" src="/js/swfupload/jquery.swfupload.js"></script>
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table content-->
        <form action="/money/save.config.money" method="post" onsubmit="return Teacher.check();">
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_base">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">编号：</td>
                      <td style="text-align:left;"><?=$this->studentMoneyRowData['student_money_data_id']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">班级信息：</td>
                        <td style="text-align:left;">
						<?=$this->studentMoneyRowData['sch_class_name']?>[<?=$this->studentMoneyRowData['sch_class_no']?>]
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">学期信息：</td>
                        <td  style="text-align:left;"><?=$this->studentMoneyRowData['sch_term_name']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">学生名称：</td>
                      <td  style="text-align:left;">
					  <?=$this->studentMoneyRowData['sch_student_name']?>[<?=$this->studentMoneyRowData['sch_student_no']?>]
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">费用编号：</td>
                      <td  style="text-align:left;"><?=$this->studentMoneyRowData['item_money']['money_number']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">费用日期：</td>
                        <td  style="text-align:left;"><?=$this->studentMoneyRowData['item_money']['money_date']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">费用类型：</td>
                      <td  style="text-align:left;">
					  <?php echo $this->studentMoneyRowData['item_money']['type']==0?"收入":"支出";?>
                      </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">费用名称：</td>
                      <td  style="text-align:left;"><?=$this->studentMoneyRowData['item_money']['money_name']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">费用项目：</td>
                      <td  style="text-align:left;"><?=$this->studentMoneyRowData['item_money']['sch_money_project_name']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">应交费用：</td>
                      <td  style="text-align:left;"><?=$this->studentMoneyRowData['item_money']['money']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">实交费用：</td>
                      <td  style="text-align:left;"><?=$this->studentMoneyRowData['item_money']['realy_money']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">描述：</td>
                      <td  style="text-align:left;"><?=$this->studentMoneyRowData['item_money']['comments']?></td>
                    </tr>
                </tbody>
            </table>
            
            <div align="center">&nbsp;&nbsp;
              <input type="button" name="fanhui" 
              	value="返回学生费用列表" 
                onclick="window.location='/money/list.student.money.data<?=urldecode(base64_decode($this->from))?>'" />
          </div>
        </div>
        </form>
        <!--body table content-->


    </div>
    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
    </div>
</div>