<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/student.js' type='text/javascript'></script>
<script type="text/javascript" src="/js/my97datepicker/WdatePicker.js" ></script>
<script type="text/javascript" src="/js/swfupload/swfupload.js"></script>
<script type="text/javascript" src="/js/swfupload/jquery.swfupload.js"></script>
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>
        <!--body table title-->

        <!--body table content-->
        <form action="/money/save.config.money" method="post" onsubmit="return Teacher.check();">
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
            <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;" id="table_teacher_base">
                <tbody>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td width="150"  style="text-align:right; width:150px;">选择班级：</td>
                        <td style="text-align:left;">
						<?=$this->configMoneyData['sch_class_name']?>[<?=$this->configMoneyData['sch_class_no']?>]
                        </td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">学期编号：</td>
                        <td  style="text-align:left;"><?=$this->configMoneyData['sch_term_name']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">月份：</td>
                      <td  style="text-align:left;"><?=$this->configMoneyData['month']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:right; width:150px;">选择项目：</td>
                        <td  style="text-align:left;"><?=$this->configMoneyData['sch_money_project_name']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">收费金额：</td>
                      <td  style="text-align:left;"><?=$this->configMoneyData['money']?></td>
                    </tr>
                    <tr class="ui-widget-content jqgrow ui-row-ltr">
                      <td  style="text-align:right; width:150px;">收费说明：</td>
                      <td  style="text-align:left;"><?=$this->configMoneyData['comments']?></td>
                    </tr>
                </tbody>
            </table>
            
            <div align="center">&nbsp;&nbsp;
              <input type="button" name="fanhui" 
              	value="返回班级学期项目费用信息" 
                onclick="window.location='/money/list.config.money<?=urldecode(base64_decode($this->from))?>'" />
          </div>
        </div>
        </form>
        <!--body table content-->


    </div>
    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
    </div>
</div>