<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 35%;float: left">
<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

	<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
		  <table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
		    <tbody>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td width="100px"  style="text-align:right;">学生：</td>
                       <td style="text-align:left;">
					   <?=$this->attendanceRowData['sch_student_name']?>[<?=$this->attendanceRowData['sch_student_no']?>]
                       </td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  width="100px"  style="text-align:right;">打卡日期：</td>
                       <td  style="text-align:left;"><?=$this->attendanceRowData['attendance_date']?></td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">到校时间：</td>
                       <td  style="text-align:left;"><?=$this->attendanceRowData['come_time']?></td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">离校时间：</td>
                       <td  style="text-align:left;"><?=$this->attendanceRowData['leave_time']?></td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td  style="text-align:right;">缺勤事由：</td>
                       <td  style="text-align:left;"><?=$this->attendanceRowData['reason']?></td>
                     </tr>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                       <td colspan="2"  style="text-align:center;">
                       <input type="button" name="button" value="返回" onclick="window.location='/studentattendance/my.list<?=urldecode(base64_decode($this->from))?>'"/>			
                       </td>
                     </tr>
              </tbody>
		  </table>
            
	</div>
		<!--body table content-->
        
  </div>
    

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>

</div>