<?= $this->headTitle($this->title) ?>
<script src='/js/<?= $GLOBALS['module'] ?>/right.js' type='text/javascript'></script>
<!--条件-->
<div style="font-size: 11px">
	用户名：
      
    <select id="user_id" name="user_id" style="width:150px;" onchange="Right.getRoleDataByUserId(this.value)">
    <option value="0">请选择</option>
		<?php foreach($this->userData as $u):?>
        <option value="<?=$u['user_id']?>" <?php echo $this->userId==$u['user_id']?"selected":""?>><?=$u['real_name']?>[<?=$u['user_name']?>]</option>
        <?php endforeach;?>
	</select>
</div>
<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all">
    <div class="ui-jqgrid-view" style="width: 100%;">
        <!--body table title-->
        <div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
            <span class="ui-jqgrid-title"><?= $this->title ?></span>
        </div>


      	<!--body table content-->
        <div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
            <table cellspacing="0" cellpadding="0" border="0" style="width: 100%;">
                <tbody>
                    <tr>
                        <td><b>角色</b></td>
                        <td></td>
                        <td><b>权限</b></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td style="width:420px;">
                        <div id="div_role_id" style="float:left; width:420px; height: 500px; overflow:auto;border:1px dotted #aed0ea">抱歉，请先选择用户。</div>
                        </td>
                        <td></td>
                        <td style="width:420px;">
                        <div id="div_right_id" style="float:left; width:420px; height: 500px; overflow:auto;border:1px dotted #aed0ea">抱歉，请先选择某角色。</div>
                        </td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
  		</div>
        <!--body table content-->

    </div>

    <!--带分页-->
    <div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;"></div>

</div>