<?= $this->headTitle( $this->title ) ?>
<script src='/js/<?=$GLOBALS['module']?>/resource.js' type='text/javascript'></script>
<!--条件-->
<form action="/resource/list.app" method="post">
<div style="font-size: 11px;">
	应用名称：
	<input type="text" id="app_name" name="app_name" style="width:120px;"  value="<?=$this->appName?>" />
	(支持模糊查询)
	<button type="submit" id="submitButton" style="margin-left:20px;">
		Search
	</button>
    <button type="button" id="addButton" style="margin-left:20px;" onclick="window.location='/resource/add.app'">
		添加应用资源
	</button>
</div>
</form>

<!--body-->
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 50%;float: left">
	<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

		<!--body table header-->
		<div class="ui-state-default ui-jqgrid-hdiv" style="width: 100%;">
			<table class="ui-jqgrid-htable" style="width:100%" cellspacing="0" cellpadding="0" border="0">
				<thead>
					<tr class="ui-jqgrid-labels">
						<th class="ui-state-default ui-th-column ui-th-ltr">应用名称</th>
						<th class="ui-state-default ui-th-column ui-th-ltr">应用字符串</th>
						<th class="ui-state-default ui-th-column ui-th-ltr">状态</th>
                        <th class="ui-state-default ui-th-column ui-th-ltr">操作</th>
					</tr>
				</thead>
			</table>
		</div>
		<!--body table header-->

		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
			<table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
				<tbody>
					<?php foreach( $this->data as $v ): ?>
                     <tr class="ui-widget-content jqgrow ui-row-ltr">
                        <td  style="text-align:center;"><?=$v['app_name']?></td>
						<td  style="text-align:center;"><?=$v['app_string']?></td>
                        <td  style="text-align:center;"><?php if($v['status']==1):?><font style="color:green;cursor:pointer"  onclick="Resource.updateAppStatus(<?=$v['app_id']?>,2)">已激活</font><?php else:?><font style="color:red;cursor:pointer" onclick="Resource.updateAppStatus(<?=$v['app_id']?>,1)">未激活</font><?php endif;?></td>
						<td  style="text-align:center;"><a href="/resource/view.app/app_id/<?=$v['app_id']?>">[查看]</a> <a href="/resource/edit.app/app_id/<?=$v['app_id']?>">[修改]</a> <a onclick="if(window.confirm('确定要删除吗?')){return true;}else{return false;}" href="/resource/delete.app/app_id/<?=$v['app_id']?>">[删除]</a></td>
					</tr>
					<?php endforeach ; ?>
                </tbody>
			</table>
		</div>
		<!--body table content-->



	</div>

	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>

</div>