<?= $this->headTitle( $this->title ) ?>
<script src='/js/<?=$GLOBALS['module']?>/resource.js' type='text/javascript'></script>
<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" style="width: 50%;float: left">
	<div class="ui-jqgrid-view" style="width: 100%;">
		<!--body table title-->
		<div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
			<span class="ui-jqgrid-title"><?= $this->title ?></span>
		</div>
		<!--body table title-->

		<!--body table content-->
		<div class="ui-jqgrid-bdiv" style="height: 100%; width: 100%;">
        	<form action="/resource/add.app.ok" method="post" onsubmit="return Resource.addApp();">
			<table cellspacing="0" cellpadding="0" border="0" class="ui-jqgrid-btable" style="width: 100%;">
				<tbody>
					<tr class="ui-widget-content jqgrow ui-row-ltr">
						<td  style="text-align:right; width:150px;">应用名称：</td>
						<td  style="text-align:left;"><?=$this->appData['app_name']?></td>
					</tr>
					<tr class="ui-widget-content jqgrow ui-row-ltr">
						<td  style="text-align:right; width:150px;">应用字符串：</td>
						<td  style="text-align:left;"><?=$this->appData['app_string']?></td>
					</tr>
					<tr class="ui-widget-content jqgrow ui-row-ltr">
						<td  style="text-align:right; width:150px;">排序：</td>
						<td  style="text-align:left;"><?=$this->appData['sort']?></td>
					</tr>
					<tr class="ui-widget-content jqgrow ui-row-ltr">
						<td  style="text-align:right; width:150px;">描述：</td>
						<td  style="text-align:left;"><?=$this->appData['comments']?></td>
					</tr>
					<tr class="ui-widget-content jqgrow ui-row-ltr">
					  <td  style="text-align:right; width:150px;">状态：</td>
					  <td  style="text-align:left;"><?php echo $this->appData['status']==1?"<font color='green'>已激活</font>":"<font color='red'>未激活</font>"?></td>
				  </tr>
					<tr class="ui-widget-content jqgrow ui-row-ltr">
						<td colspan="2"  style="text-align:center; width:150px;"><input type="button" name="fan" value="返回应用列表" onclick="window.location='/resource/list.app'" /></td>
					</tr>
				</tbody>
			</table>
            </form>
		</div>
		<!--body table content-->


	</div>
	<!--带分页-->
	<div class="ui-state-default ui-jqgrid-pager ui-corner-bottom" style="width: 100%;">
	</div>
</div>